apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment          
  labels:
    app: myapp
spec:
  replicas: 3                    
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: 227295996532.dkr.ecr.us-east-1.amazonaws.com/sampleapp:cf622df
          ports:
            - containerPort: 5000    
          
