apiVersion: v1
kind: Service
metadata:
  name: myapp-service            
  labels:
    app: myapp
spec:
  type: LoadBalancer             
  selector:
    app: myapp
  ports:
    - name: http
      protocol: TCP
      port: 80                  
      targetPort: 5000    
